version: "3.9"

services:
  web:
    build:
      context: .
    command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes: []
