production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_production' } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>

cable:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_production' } %>_cable
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
