# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'myuser' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'mypassword' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB") { 'myapp_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_production' } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
